<?php
$z[0]=Array("global","",794,820);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",864,894);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",931,958);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",1331,1357);
$z[3][4]['name']="cfg_cmspath";
$z[4]=Array("global","",1530,1556);
$z[4][4]['name']="cfg_cmspath";
$z[5]=Array("channelartlist","\r\n                <li class=\"{dede:field.currentstyle/}\"><a href=\"{dede:field name='typeurl'/}\" target=\"_self\">{dede:field name='typename'/}</a>\r\n                <div>\r\n                    <ul>\r\n                    {dede:channel type='son' noself='yes'}\r\n                    <li><a href=\"[field:typelink/]\" target=\"_self\">[field:typename/]</a></li>\r\n                    {/dede:channel}\r\n                    </ul>\r\n                </div>\r\n                </li>\r\n                ",1727,2283);
$z[5][4]['typeid']="top";
$z[5][4]['currentstyle']="current";
$z[6]=Array("type","[field:typeurl/]",3638,3688);
$z[6][4]['typeid']="9";
$z[7]=Array("type","[field:typeurl/]",4648,4698);
$z[7][4]['typeid']="8";
$z[8]=Array("type","[field:typeurl/]",5304,5355);
$z[8][4]['typeid']="10";
$z[9]=Array("arclist","\r\n                                        <li><a href=\"[field:arcurl/]\" target=\"_blank\"><img onload=\"loadImage(this,244,367);\" src=\"[field:litpic/]\" /></a></li>\r\n                        ",6466,6712);
$z[9][4]['typeid']="16";
$z[9][4]['row']="10";
$z[9][4]['titlelen']="32";
$z[10]=Array("arclist","\r\n                                        <li><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" /></a></li>\r\n                        ",7140,7352);
$z[10][4]['typeid']="15";
$z[10][4]['row']="10";
$z[10][4]['titlelen']="32";
$z[11]=Array("arclist","\r\n                                        <li><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" /></a></li>\r\n                        ",7756,7968);
$z[11][4]['typeid']="17";
$z[11][4]['row']="10";
$z[11][4]['titlelen']="32";
$z[12]=Array("include","",8812,8849);
$z[12][4]['filename']="footer.htm";

?>